import React from 'react';
import { ChatMessage as ChatMessageType } from '../types';

interface ChatMessageProps {
  message: ChatMessageType;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const { role, text, imageUrl, sources } = message;
  const isModel = role === 'model';
  const isLoading = text === 'กำลังพิมพ์...';

  const bubbleClasses = isModel
    ? 'bg-gray-200 text-gray-800 self-start rounded-bl-none'
    : 'bg-orange-500 text-white self-end rounded-br-none';
  
  const containerClasses = isModel ? 'flex justify-start' : 'flex justify-end';
  const labelText = isModel ? 'RightCode Buddy ตอบว่า' : 'คุณพูดว่า';
  
  const handleDownload = (e: React.MouseEvent<HTMLAnchorElement>) => {
      e.preventDefault();
      const link = document.createElement('a');
      link.href = imageUrl!;
      link.download = `RightCodeBuddy-Image-${Date.now()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
  }

  return (
    <div className={`flex flex-col ${isModel ? 'items-start' : 'items-end'}`}>
        <p className="text-xs text-gray-500 px-2 mb-1">{labelText}</p>
        <div className={containerClasses}>
          <div className={`max-w-xs md:max-w-lg p-3 rounded-lg shadow-sm flex flex-col gap-2 ${bubbleClasses}`}>
            {imageUrl && (
                <div className="relative group">
                    <img src={imageUrl} alt={isModel ? "Generated by AI" : "User upload"} className="rounded-lg max-w-full h-auto" />
                    <a 
                        href={imageUrl}
                        onClick={handleDownload}
                        className="absolute top-2 right-2 bg-black bg-opacity-50 text-white rounded-full w-8 h-8 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
                        aria-label="Download image"
                        title="Download Image"
                    >
                        <i className="fas fa-download"></i>
                    </a>
                </div>
            )}
            {text && (
                <p className={`text-sm whitespace-pre-wrap ${isLoading ? 'animate-pulse' : ''}`}>{text}</p>
            )}
            {sources && sources.length > 0 && (
                <div className="mt-2 border-t border-gray-300 pt-2">
                    <h4 className="text-xs font-bold text-gray-500 mb-1">แหล่งข้อมูล:</h4>
                    <ul className="space-y-1">
                        {sources.map((source, index) => (
                            <li key={index}>
                                <a 
                                    href={source.uri} 
                                    target="_blank" 
                                    rel="noopener noreferrer"
                                    className="text-xs text-green-600 hover:underline truncate block"
                                >
                                    <i className="fas fa-link mr-1"></i> {source.title || source.uri}
                                </a>
                            </li>
                        ))}
                    </ul>
                </div>
            )}
          </div>
        </div>
    </div>
  );
};

export default ChatMessage;